#define MICROPY_HW_BOARD_NAME "Planter ESP32 ROMFS"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MICROPY_VFS_ROM (1)
#define MICROPY_VFS_ROM_IOCTL (1)
#define MICROPY_PY_BLUETOOTH (0)
#define MICROPY_PY_NETWORK_LAN (0)
